#!/usr/bin/env python3
"""Generic odd-degree B-spline correlations for mixed-order Weil dictionaries.

Proof-path arithmetic is rational interval arithmetic except for documented
outward-rounded Decimal.exp in weil_interval_core.  This module supports the
correlation degrees 3, 5, and 7 generated by basis degrees 1 and 3.
"""
from __future__ import annotations
from fractions import Fraction as F
from math import comb, factorial
from typing import List, Sequence, Tuple

import weil_interval_core as base
from rigorous_refinement_tools import tail_sum_power_refined


def halfwidth_units(degree: int) -> int:
    if degree < 1 or degree % 2 == 0:
        raise ValueError("this package expects positive odd correlation degree")
    return (degree + 1) // 2


def beta_affine_piece(degree: int, h: F, center: F, sign: int, midpoint: F) -> List[F]:
    """Polynomial for beta_degree((sign*x-center)/h) on one knot interval."""
    radius = halfwidth_units(degree)
    zmid = (sign * midpoint - center) / h
    out = [F(0)] * (degree + 1)
    for k in range(degree + 2):
        shift = F(radius - k)
        if zmid + shift > 0:
            alpha = F(sign) / h
            beta = -center / h + shift
            term = base.linear_power(alpha, beta, degree)
            coeff = F((-1) ** k * comb(degree + 1, k), factorial(degree))
            out = base.poly_add(out, base.poly_scale(term, coeff))
    return out


def support(degree: int, h: F, center: F) -> Tuple[F, F]:
    radius = F(halfwidth_units(degree)) * h
    return center - radius, center + radius


def knots(degree: int, h: F, center: F) -> List[F]:
    radius = halfwidth_units(degree)
    return [center + h * k for k in range(-radius, radius + 1)]


def f_piece(degree: int, h: F, center: F, midpoint: F, sign: int = 1) -> List[F]:
    return beta_affine_piece(degree, h, center, sign, midpoint)


def f_value(degree: int, h: F, center: F, x: F) -> F:
    left, right = support(degree, h, center)
    if x < left or x > right:
        return F(0)
    radius = halfwidth_units(degree)
    z = (x - center) / h
    out = F(0)
    for k in range(degree + 2):
        y = z + F(radius - k)
        if y > 0:
            out += F((-1) ** k * comb(degree + 1, k), factorial(degree)) * y ** degree
    return out


def f_interval(degree: int, h: F, center: F, x: base.IV) -> base.IV:
    left, right = support(degree, h, center)
    if x.hi < left or x.lo > right:
        return base.IV.point(0)
    if x.lo < left or x.hi > right:
        raise ArithmeticError("sample interval crosses support boundary")
    containing = [
        (a, b)
        for a, b in zip(knots(degree, h, center)[:-1], knots(degree, h, center)[1:])
        if a <= x.lo and x.hi <= b
    ]
    if len(containing) != 1:
        # Exact endpoint samples have value zero and may touch two pieces.
        if x.lo == x.hi and x.lo in knots(degree, h, center):
            return base.IV.point(f_value(degree, h, center, x.lo))
        raise ArithmeticError("sample interval crosses a spline knot")
    a, b = containing[0]
    p = f_piece(degree, h, center, (a + b) / 2)
    return base.coarsen(base.poly_eval_iv(p, x), 70)


def integrate_f_exp(degree: int, h: F, center: F, lam: F) -> base.IV:
    ks = knots(degree, h, center)
    total = base.IV.point(0)
    for left, right in zip(ks[:-1], ks[1:]):
        p = f_piece(degree, h, center, (left + right) / 2)
        total += base.integrate_poly_exp_iv(p, lam, left, right)
    return base.coarsen(total, 75)


def even_sum_pieces(degree: int, h: F, center: F):
    left, right = support(degree, h, center)
    radius = max(abs(left), abs(right))
    split = {F(0), radius}
    for q in knots(degree, h, center):
        if 0 < q < radius:
            split.add(q)
        if 0 < -q < radius:
            split.add(-q)
    ordered = sorted(split)
    pieces = []
    for a, b in zip(ordered[:-1], ordered[1:]):
        mid = (a + b) / 2
        p_pos = f_piece(degree, h, center, mid, 1) if left < mid < right else [F(0)]
        p_neg = f_piece(degree, h, center, mid, -1) if left < -mid < right else [F(0)]
        pieces.append((a, b, base.poly_add(p_pos, p_neg)))
    return radius, pieces


def laplace_even_sum(degree: int, h: F, center: F, a: F, pieces) -> base.IV:
    return base.iv_sum(
        base.integrate_poly_exp_iv(poly, -a, left, right)
        for left, right, poly in pieces
    )


def derivative_data(degree: int, pieces):
    first = pieces[0][2]
    even_orders = tuple(range(0, degree, 2))
    values = [base.poly_eval(base.poly_derivative(first, order), F(0)) for order in even_orders]
    bound = F(0)
    for left, right, poly in pieces:
        deriv = base.poly_derivative(poly, degree)
        bound = max(bound, abs(base.poly_eval(deriv, left)), abs(base.poly_eval(deriv, right)))
    return even_orders, values, bound


def arch_series_generic(degree: int, h: F, center: F, K: int, cutoff: int = 20000):
    """Rigorous archimedean term for odd correlation degrees 3,5,7.

    For a=2k+1/2, integrate by parts through derivative degree-1 and bound
    the piecewise-constant degree-th derivative remainder.  The resulting
    tail order is O(K^-degree).
    """
    radius, pieces = even_sum_pieces(degree, h, center)
    fzero = f_value(degree, h, center, F(0))
    orders, derivs, B = derivative_data(degree, pieces)
    if derivs[0] != 2 * fzero:
        raise AssertionError("even-sum normalization mismatch")

    partial = base.IV.point(0)
    leading_partial = F(0)
    for k in range(K):
        aa = F(4 * k + 1, 2)
        bb = F(2 * k + 1)
        integral = laplace_even_sum(degree, h, center, aa, pieces)
        partial = base.coarsen(partial + integral - base.IV.point(derivs[0] / bb), 72)
        leading_partial += F(1, aa) - F(1, bb)

    leading_total = base.pi_iv().scale(F(1, 4)) + base.log_rational_iv(F(2), 170).scale(F(1, 2))
    leading_tail = (leading_total - base.IV.point(leading_partial)).scale(derivs[0])

    known_tail = base.IV.point(0)
    known_terms = {}
    for order, value in zip(orders[1:], derivs[1:]):
        power = order + 1
        term = tail_sum_power_refined(K, power, cutoff).scale(value)
        known_tail += term
        known_terms[str(power)] = base.iv_json(term)

    remainder_power = degree + 1
    remainder_sum = tail_sum_power_refined(K, remainder_power, cutoff)
    remainder = base.IV(-B * remainder_sum.hi, B * remainder_sum.hi)
    tail = leading_tail + known_tail + remainder
    arch = base.coarsen(-(partial + tail), 70)
    audit = {
        "degree": degree,
        "radius": base.frac_json(radius),
        "series_terms": K,
        "tail_rational_cutoff": cutoff,
        "even_derivatives": {str(o): base.frac_json(v) for o, v in zip(orders, derivs)},
        "degree_derivative_sup": base.frac_json(B),
        "leading_tail": base.iv_json(leading_tail),
        "known_power_tails": known_terms,
        "remainder_power": remainder_power,
        "remainder_tail": base.iv_json(remainder),
        "tail_interval": base.iv_json(tail),
        "partial": base.iv_json(partial),
        "arch": base.iv_json(arch),
        "method": "signed even-derivative expansion plus rational power-tail continuation",
    }
    return arch, audit
