#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Corpus Engine build orchestrator (was build.py main()).
Run: python scripts/build.py  |  python -m scripts.build  |  python build.py"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import html
import json
import re
import shutil
import unicodedata
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote
from scripts.config import *
from scripts.helpers import *
from scripts.render import *
from scripts.render import _MD_BACKEND
from scripts.generators import *
from scripts.registry import build_registry, save_registry
from scripts.idroutes import (write_id_pages, write_raw_files, write_api,
                              write_redirects, write_legacy_map,
                              write_sitemap_canonical)
from scripts.validate import validate_routes, validate_links
from scripts.ai_layer import write_ai_layer
from scripts.graph_layer import write_graph_layer
from scripts.companions import write_companions
from scripts.geo_layer import write_geo_layer


def main() -> None:
    if not PAPERS_DIR.exists():
        print(f"[warn] {PAPERS_DIR} not found; creating empty directory.")
        PAPERS_DIR.mkdir()

    if DIST_DIR.exists():
        shutil.rmtree(DIST_DIR)
    DIST_DIR.mkdir()

    files = sorted(
        p for p in PAPERS_DIR.rglob("*")
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS
    )

    seen: dict[str, Path] = {}
    entries: list[tuple[str, str, str, Path]] = []
    for idx, f in enumerate(files):
        base = make_slug(f.name, idx)
        slug = base
        n = 1
        while slug in seen:
            bp = Path(base)
            slug = f"{bp.stem}-{n}{bp.suffix}"
            n += 1
        seen[slug] = f
        entries.append((slug, f.stem, f.suffix.lower().lstrip("."), f))

    zh_entries = sorted([e for e in entries if has_cjk(e[1])], key=lambda x: x[1])
    en_entries = sorted([e for e in entries if not has_cjk(e[1])], key=lambda x: x[1])

    # Stable-identity registry is the source of truth; build it BEFORE the hub
    # generators so they can emit id-native (/p/{id}/) links and KV keys.
    registry = build_registry(entries)
    save_registry(registry)

    write_metadata_json(registry, DIST_DIR)  # 生成 papers-metadata.json (id-native)
    write_cosmomind(registry, entries, DIST_DIR)  # 生成星環導航頁
    write_base_space(registry, DIST_DIR)  # 生成星環矩陣底空間頁
    write_deconstruction(registry, entries, DIST_DIR)  # 生成認知解構學交互實驗室頁面
    write_index(zh_entries, en_entries, registry)
    write_manifest(zh_entries, en_entries, DIST_DIR)
    write_robots()
    # canonical /llms.txt + /llms-full.txt are generated by write_ai_layer below (§26.7.6)
    # --- Phase 2/4: stable-identity + AICL /ai/ layer + deterministic-ingestion validation ---
    geo_layer = write_geo_layer(registry, entries)  # GEO: Q&A H2 + definition-block signals (warn-only lint)
    id_pages = write_id_pages(registry, entries, geo_layer["per_id"])
    write_raw_files(registry, entries)
    companions = write_companions(registry)  # C layer: attachments -> /raw/{parent}/ + /ai/companions.json + retired-id 301 map
    write_api(registry)
    write_redirects(registry, companions)
    write_legacy_map(registry, companions)  # dist/papers-legacy-map.json for the /papers/* catch-all Function
    ai_count = write_ai_layer(registry, entries)  # §9 AICL /ai/ + §10 AIRS + canonical llms
    graph_stats = write_graph_layer(registry)  # Phase A: registry/tcf/ -> /ai/graph.json (real topology)
    write_sitemap_canonical(registry)          # §26.6.6 canonical-only sitemap (replaces legacy)
    route_issues = validate_routes(registry)   # §26.7 route consistency report
    broken_links = validate_links(registry)    # §26.5.7 broken-link report (warn-only)

    print(f"[diag] build.py version: AIO-v3.1 (id-native /p/{{id}}/)")
    print(f"[diag] markdown backend: {_MD_BACKEND}")
    print(f"[diag] source papers/ scanned: {len(files)} files")
    print(f"[diag] id pages: {id_pages} canonical /p/{{id}}/ (legacy /papers/ retired -> [[path]].js)")
    print(f"[diag] language split: {len(zh_entries)} zh-Hant / {len(en_entries)} en")
    print(f"[diag] registry: {registry['count']} stable ids | +/p +/raw +/api +_redirects (id pages: {id_pages})")
    print(f"[diag] AICL: /ai/ layer + rights-spectrum + canonical llms ({ai_count} corpus.jsonl lines)")
    print(f"[diag] companions: {companions['attachments']} attachment(s) under {companions['parents']} paper(s) "
          f"-> /raw/{{parent}}/ + /ai/companions.json | retired ids: {companions['retired'] or '—'} "
          f"| missing: {companions['missing'] or '—'}")
    if graph_stats["mapped"]:
        print(f"[diag] graph: /ai/graph.json — {graph_stats['mapped']} nodes / {graph_stats['edges']} verified edges "
              f"(candidates: {graph_stats.get('candidates', 0)}, rejected: {graph_stats.get('rejected', 0)}, "
              f"pending audit: {graph_stats.get('pending_audit', 0)}, unresolved refs: {graph_stats.get('unresolved', 0)}, "
              f"tcf errors: {len(graph_stats['errors'])})")
    else:
        print(f"[diag] graph: no registry/tcf/ extractions yet -> base-space stays on simulated seed")
    print(f"[diag] validate: route-issues={len(route_issues)} | broken-internal-links={len(broken_links)} (warn-only) -> registry/generated/")
    print(f"[diag] geo: {geo_layer['scanned']} md papers scanned | {geo_layer['with_signals']} with Q&A/definition signals "
          f"| {len(geo_layer['findings'])} lint findings (warn-only) -> registry/generated/geo-lint.json")
    for i, it in enumerate(registry["items"][:5]):
        print(f"        [{i+1}] {it['title']!r:36s} -> {it['id']}  ({it['canonical_url']})")

    bad = []
    for p in DIST_DIR.rglob("*"):
        if p.is_file():
            try:
                p.name.encode("ascii")
            except UnicodeEncodeError:
                bad.append(str(p.relative_to(DIST_DIR)))
    if bad:
        print(f"[diag] WARNING: {len(bad)} non-ASCII filename(s) in dist/")
    else:
        print(f"[diag] OK: all {sum(1 for _ in DIST_DIR.rglob('*') if _.is_file())} files in dist/ are ASCII-safe")

    print(f"[ok] Build complete. {len(entries)} papers, {id_pages} id pages -> {DIST_DIR}")


if __name__ == "__main__":
    main()
